### ISSUE TITLE
OSC52 support (copying in remote terminals)

### ISSUE THREAD

**Issue by tombh** [replydev/cotp#68]
Thanks for the great app, it's exactly what I'm looking for ✨

I'm using it on a remote server, would you be interested in OSC52 support? It may be possible to implement with Cargo's [copypasta-ext](https://docs.rs/copypasta-ext/0.3.7/copypasta_ext/osc52/index.html). I'm happy to try a PR if it would help.

Also, would you be interested in a setting to reduce the line spacing?

**Comment by replydev** [comment]
Hello and thank you🙂.
I think that the OSC52 support is very interesting, so if you can please implement the feature and send a PR. Otherwise i will implement it myself when i got some time.
I will check if we could reduce line spacing, hoping the screen will not become less readable.

Thank you again, kind regards.
